CREATE SCHEMA IF NOT EXISTS account;
CREATE SCHEMA IF NOT EXISTS predefined;
CREATE SCHEMA IF NOT EXISTS blog;
CREATE SCHEMA IF NOT EXISTS conversation;
CREATE SCHEMA IF NOT EXISTS customer;
CREATE SCHEMA IF NOT EXISTS toy;
CREATE SCHEMA IF NOT EXISTS task;

CREATE SEQUENCE account.seq_cycle MAXVALUE 100000000 CYCLE;
CREATE SEQUENCE predefined.seq_cycle MAXVALUE 100000000 CYCLE;
CREATE SEQUENCE blog.seq_cycle MAXVALUE 100000000 CYCLE;
CREATE SEQUENCE conversation.seq_cycle MAXVALUE 100000000 CYCLE;
CREATE SEQUENCE customer.seq_cycle MAXVALUE 100000000 CYCLE;
CREATE SEQUENCE toy.seq_cycle MAXVALUE 100000000 CYCLE;
CREATE SEQUENCE task.seq_cycle MAXVALUE 100000000 CYCLE;