version: '3.7'
name: test
services:
  minio:
    container_name: ${MINIO_NAME}
    image: minio/minio
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_UI_PORT}:9090
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME:-}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-}
    volumes:
      - minio:/data
    command: server /data --console-address :9090
    networks:
      - bridge

#  minio-mc:
#    container_name: ${MINIO_MC_NAME}
#    image: minio/mc
#    depends_on:
#      - minio
#    entrypoint: >
#      /bin/sh -c "
#      /usr/bin/mc config host add local http://minio:9000 ${MINIO_USERNAME} ${MINIO_PASSWORD};
#      /usr/bin/mc mb local/${MINIO_BUCKET_NAME};
#      exit 0;
#      "
#    networks:
#      - bridge

  redis:
    container_name: ${REDIS_NAME}
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --bind ${REDIS_BIND} --maxmemory ${REDIS_MAX_MEMORY} --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    networks:
      - bridge

  elasticsearch:
    container_name: ${ELASTICSEARCH_NAME}
    image: elasticsearch:8.7.0
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TCP_PORT}:9300"
    volumes:
      - ${ELASTICSEARCH_CONFIG_VOLUME}:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      discovery.type: single-node
    networks:
      - bridge

  postgres:
    container_name: ${POSTGRES_NAME}
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_INIT}:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: postgres -c log_destination=stderr -c log_statement=all -c max_connections=${POSTGRES_MAX_CONNECTIONS}
    networks:
      - bridge

networks:
  bridge:
    name: test
    driver: bridge

volumes:
  minio:
    name: ${MINIO_VOLUME}
  redis:
    name: ${REDIS_VOLUME_NAME}
  elasticsearch:
    name: ${ELASTICSEARCH_VOLUME_NAME}
  postgres:
    name: ${POSTGRES_VOLUME_NAME}
