eureka:
  client:
    enabled: false

spring:
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:40600/postgres
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 40400
      password: redis-password

  elasticsearch:
    uris: http://localhost:40500
    password: elasticsearch-password

  kafka:
    bootstrap-servers: localhost:40302

  docker:
    compose:
      enabled: true
      file: classpath:docker/docker-compose.yml

logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: debug
    org.hibernate.SQL_SLOW: info
    org.hibernate.cache: debug
    org.springframework.data.elasticsearch.core: debug
    org.elasticsearch.client: debug
    org.apache.http: debug
    p6spy: info

freshr:
  minio:
    host: http://localhost:10501
    bucket: test
    access: minio-username
    secret: minio-password
