eureka:
  client:
    service-url:
      defaultZone: https://staging.discovery.freshr.run/eureka/

spring:
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        SQL: info
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: info

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://staging.freshr.run:40603/postgres
    username: postgres
    password: postgres

  data:
    redis:
      host: https://staging.freshr.run
      port: 40400
      password: redis-password

  elasticsearch:
    uris: https://staging.freshr.run:40500
    password: elasticsearch-password

freshr:
  minio:
    host: http://staging.freshr.run:10501
    bucket: freshr-staging
    access: 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
    secret: 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
