eureka:
  client:
    service-url:
      defaultZone: http://localhost:40700/eureka/

spring:
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        SQL: trace
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:40603/postgres
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 40400
      password: redis-password

  elasticsearch:
    uris: http://localhost:40500
    password: elasticsearch-password

logging:
  level:
    root: info

freshr:
  minio:
    host: http://localhost:10501
    bucket: test
    access: minio-username
    secret: minio-password
