version: '3.8'
name: blog-global
services:
  minio:
    container_name: ${MINIO_NAME}
    image: minio/minio
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_UI_PORT}:9090
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME:-}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-}
    volumes:
      - minio:/data
    command: server /data --console-address :9090
    networks:
      - bridge

  minio-mc:
    container_name: ${MINIO_MC_NAME}
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add local http://minio:9000 ${MINIO_USERNAME} ${MINIO_PASSWORD};
      /usr/bin/mc mb local/${MINIO_BUCKET_NAME};
      exit 0;
      "
    networks:
      - bridge

networks:
  bridge:
    name: blog-infra
    driver: bridge

volumes:
  minio:
    name: minio